services:
  db:
    image: postgres:14-alpine
    container_name: angel-of-the-dices-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aotd_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata: